language: python

python:
  - '3.8'

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment

install:
  - conda install -c conda-forge mpi
  - conda install -c conda-forge imagemagick
  - make install

addons:
  sonarcloud:
    organization: 'viktorc-github'
    token: $SONAR_TOKEN

script:
  - make lint
  - make type-check
  - make coverage
  - sonar-scanner