language: python

python:
  - '3.6'
  - '3.7'
  - '3.8'

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment

install:
  - conda install -c anaconda mpi4py~=3.0.3
  - conda install -c conda-forge fipy==3.3
  - make install

script:
  - make lint
  - make test