name: Build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install MPI
      run: |
        sudo apt install -y -q mpich libmpich-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install
    - name: Lint
      run: |
        make lint
    - name: Type-check
      run: |
        make type-check
    - name: Test
      run: |
        make coverage
    - name: Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}